const ActionTypes = {
  HIDE_MODAL: 'HIDE_MODAL',
  SHOW_MODAL: 'SHOW_MODAL',
  REQUEST_AUTH: 'REQUEST_AUTH',
  RECEIVE_AUTH: 'RECEIVE_AUTH',
  REQUEST_LOGOUT: 'REQUEST_LOGOUT',
  RECEIVE_LOGOUT: 'RECEIVE_LOGOUT',
  REQUEST_SIGNUP: 'REQUEST_SIGNUP',
  RECEIVE_SIGNUP: 'RECEIVE_SIGNUP',
  RECEIVE_COOKIE: 'RECEIVE_COOKIE',
  RECEIVE_TOKENS: 'RECEIVE_TOKENS',
  ADD_TOKEN: 'ADD_TOKEN',
  DELETE_TOKEN: 'DELETE_TOKEN',
  RECEIVE_BALANCES: 'RECEIVE_BALANCES',
  RECEIVE_CREATE_TOKENS: 'RECEIVE_CREATE_TOKENS',
  UPDATE_SETTINGS: 'UPDATE_SETTINGS'
};

export default ActionTypes;