const ActionTypes = {
  HIDE_MODAL: 'HIDE_MODAL',
  SHOW_MODAL: 'SHOW_MODAL',
  REQUEST_AUTH: 'REQUEST_AUTH',
  RECEIVE_AUTH: 'RECEIVE_AUTH',
  REQUEST_LOGOUT: 'REQUEST_LOGOUT',
  RECEIVE_LOGOUT: 'RECEIVE_LOGOUT'
};

export default ActionTypes;